package javaccproject;
/* Generated By:JavaCC: Do not edit this line. Exp1Visitor.java Version 6.0_1 */
public interface Exp1Visitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=2182ddc085e9dbb4c73a39b8244d95bd (do not edit this line) */
