package javaccproject;

/* Generated By:JavaCC: Do not edit this line. Exp1TreeConstants.java Version 6.0_1 */
public interface Exp1TreeConstants
{
  public int JJT__START = 0;
  public int JJT__CLASS = 1;
  public int JJT__SUPER = 2;
  public int JJT__MEMBER = 3;
  public int JJT__MODIFIER = 4;
  public int JJT__MEMBER_P = 5;
  public int JJT__MEMBERID = 6;
  public int JJT__FORMALARGS = 7;
  public int JJT__FORMALARGLIST = 8;
  public int JJT__FORMALARG = 9;
  public int JJT__TYPE = 10;
  public int JJT__TYPE_P = 11;
  public int JJT__PRIMITIVETYPE = 12;
  public int JJT__VARDECLARATORID = 13;
  public int JJT__BLOCK = 14;
  public int JJT__STATEMENT = 15;
  public int JJT__VARDECLARATORLIST = 16;
  public int JJT__VARDECLARATORLISTPREID = 17;
  public int JJT__VARDECLARATOR = 18;
  public int JJT__VARDECLARATORPREID = 19;
  public int JJT__EXPRESSION = 20;
  public int JJT__EXPRESSION_P = 21;
  public int JJT__EXPRESSION_P_P = 22;
  public int JJT__EXPRESSION_P_P_P = 23;
  public int JJT__EXPRESSION_P_P_P_P = 24;
  public int JJT__EXPRESSION_P_P_P_P_P = 25;
  public int JJT__EXPRESSION_P_P_P_P_P_P = 26;
  public int JJT__EXPRESSION_P_P_P_P_P_P_P = 27;
  public int JJT__EXPRESSIONA_P = 28;
  public int JJT__EXPRESSIONA_P_P = 29;
  public int JJT__EXPRESSIONA_P_P_P = 30;
  public int JJT__EXPRESSIONA_P_P_P_P = 31;
  public int JJT__EXPRESSIONA_P_P_P_P_P = 32;
  public int JJT__EXPRESSIONA_P_P_P_P_P_P = 33;
  public int JJT__EXPRESSIONA_P_P_P_P_P_P_P = 34;
  public int JJT__BINARYOPSEVEN = 35;
  public int JJT__BINARYOPSIX = 36;
  public int JJT__BINARYOPFIVE = 37;
  public int JJT__BINARYOPFOUR = 38;
  public int JJT__BINARYOPTHREE = 39;
  public int JJT__BINARYOPTWO = 40;
  public int JJT__BINARYOPONE = 41;
  public int JJT__UNARYOP = 42;
  public int JJT__PRIMARY = 43;
  public int JJT__PRIMARYREAL = 44;
  public int JJT__NONNEWARRAYEXPR = 45;
  public int JJT__LITERAL = 46;
  public int JJT__DIMPLUS_P = 47;
  public int JJT__DIMENSION = 48;
  public int JJT__PRIMARYID = 49;
  public int JJT__ACTUALARGS = 50;
  public int JJT__EXPRLIST = 51;
  public int JJT__PRIMARYNEW = 52;
  public int JJT__ACTUALDIM = 53;
  public int JJT__DIMPLUS = 54;
  public int JJT__MEMBER_P_P = 55;
  public int JJT__MEMBER_P_PPREID = 56;
  public int JJT__FIELD = 57;
  public int JJT__METHODCTORCOMBO = 58;


  public String[] jjtNodeName = {
    "__Start",
    "__Class",
    "__Super",
    "__Member",
    "__Modifier",
    "__Member_p",
    "__MemberId",
    "__FormalArgs",
    "__FormalArgList",
    "__FormalArg",
    "__Type",
    "__Type_p",
    "__PrimitiveType",
    "__VarDeclaratorId",
    "__Block",
    "__Statement",
    "__VarDeclaratorList",
    "__VarDeclaratorListPreId",
    "__VarDeclarator",
    "__VarDeclaratorPreId",
    "__Expression",
    "__Expression_p",
    "__Expression_p_p",
    "__Expression_p_p_p",
    "__Expression_p_p_p_p",
    "__Expression_p_p_p_p_p",
    "__Expression_p_p_p_p_p_p",
    "__Expression_p_p_p_p_p_p_p",
    "__ExpressionA_p",
    "__ExpressionA_p_p",
    "__ExpressionA_p_p_p",
    "__ExpressionA_p_p_p_p",
    "__ExpressionA_p_p_p_p_p",
    "__ExpressionA_p_p_p_p_p_p",
    "__ExpressionA_p_p_p_p_p_p_p",
    "__BinaryOpSeven",
    "__BinaryOpSix",
    "__BinaryOpFive",
    "__BinaryOpFour",
    "__BinaryOpThree",
    "__BinaryOpTwo",
    "__BinaryOpOne",
    "__UnaryOp",
    "__Primary",
    "__PrimaryReal",
    "__NonNewArrayExpr",
    "__Literal",
    "__DimPlus_p",
    "__Dimension",
    "__PrimaryId",
    "__ActualArgs",
    "__ExprList",
    "__PrimaryNew",
    "__ActualDim",
    "__DimPlus",
    "__Member_p_p",
    "__Member_p_pPreId",
    "__Field",
    "__MethodCtorCombo",
  };
}
/* JavaCC - OriginalChecksum=b984061d8d7a5195258c7de86c559cc0 (do not edit this line) */
